In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [0]:
df=datasets.load_digits()

In [3]:
x = pd.DataFrame(np.array(df.data))
y = pd.DataFrame(df.target)
print("shape of X : ", x.shape)
print("shape of Y : ",y.shape)
x.head()

shape of X :  (1797, 64)
shape of Y :  (1797, 1)


0    1    2     3     4     5    6    7    8    9  ...    54   55   56  \
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0 ...   5.0  0.0  0.0   
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0 ...   9.0  0.0  0.0   
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   

    57   58    59    60    61   62   63  
0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4  0.0  0.0   2.0  16.0   4.0  0.0  0.0  

[5 rows x 64 columns]

In [0]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25)

**Linear SVM**

In [5]:
from sklearn.svm import SVC
model=SVC(kernel='linear')
model.fit(x_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [0]:
y_pred=model.predict(x_test)

In [12]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,y_pred))

[[43  0  0  0  0  0  0  0  0  0]
 [ 0 40  0  0  0  0  0  0  0  0]
 [ 0  0 37  0  0  0  0  1  0  0]
 [ 0  0  0 52  0  0  0  0  0  0]
 [ 0  0  0  0 38  0  0  0  0  0]
 [ 0  0  0  0  0 49  0  0  0  1]
 [ 0  0  0  0  0  0 45  0  0  0]
 [ 0  0  0  0  0  0  0 39  0  0]
 [ 0  2  0  1  0  0  0  0 48  1]
 [ 0  0  0  1  0  0  0  0  1 51]]


In [9]:
print(classification_report(y_test,y_pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        43
          1       0.91      1.00      0.95        40
          2       0.97      1.00      0.99        38
          3       0.98      1.00      0.99        52
          4       1.00      1.00      1.00        38
          5       0.98      0.98      0.98        50
          6       1.00      1.00      1.00        45
          7       1.00      0.97      0.99        39
          8       0.94      0.87      0.90        52
          9       0.96      0.94      0.95        53

avg / total       0.97      0.97      0.97       450



**Poly SVM**

In [10]:
model=SVC(kernel='poly', degree=5)
model.fit(x_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=5, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [0]:
y_pred=model.predict(x_test)

In [13]:
print(confusion_matrix(y_test,y_pred))

[[43  0  0  0  0  0  0  0  0  0]
 [ 0 40  0  0  0  0  0  0  0  0]
 [ 0  0 37  0  0  0  0  1  0  0]
 [ 0  0  0 52  0  0  0  0  0  0]
 [ 0  0  0  0 38  0  0  0  0  0]
 [ 0  0  0  0  0 49  0  0  0  1]
 [ 0  0  0  0  0  0 45  0  0  0]
 [ 0  0  0  0  0  0  0 39  0  0]
 [ 0  2  0  1  0  0  0  0 48  1]
 [ 0  0  0  1  0  0  0  0  1 51]]


In [14]:
print(classification_report(y_test,y_pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        43
          1       0.95      1.00      0.98        40
          2       1.00      0.97      0.99        38
          3       0.96      1.00      0.98        52
          4       1.00      1.00      1.00        38
          5       1.00      0.98      0.99        50
          6       1.00      1.00      1.00        45
          7       0.97      1.00      0.99        39
          8       0.98      0.92      0.95        52
          9       0.96      0.96      0.96        53

avg / total       0.98      0.98      0.98       450



**Gassian SVM**

In [15]:
model=SVC(kernel='rbf')
model.fit(x_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [0]:
y_pred=model.predict(x_test)

In [17]:
print(confusion_matrix(y_test,y_pred))

[[28  0 15  0  0  0  0  0  0  0]
 [ 0 27 13  0  0  0  0  0  0  0]
 [ 0  0 38  0  0  0  0  0  0  0]
 [ 0  0 29 23  0  0  0  0  0  0]
 [ 0  0  4  0 34  0  0  0  0  0]
 [ 0  0 36  0  0 14  0  0  0  0]
 [ 0  0 19  0  0  0 26  0  0  0]
 [ 0  0  5  0  0  0  0 34  0  0]
 [ 0  0 51  0  0  0  0  0  1  0]
 [ 0  0 47  0  0  0  0  0  0  6]]


In [18]:
print(classification_report(y_test,y_pred))

             precision    recall  f1-score   support

          0       1.00      0.65      0.79        43
          1       1.00      0.68      0.81        40
          2       0.15      1.00      0.26        38
          3       1.00      0.44      0.61        52
          4       1.00      0.89      0.94        38
          5       1.00      0.28      0.44        50
          6       1.00      0.58      0.73        45
          7       1.00      0.87      0.93        39
          8       1.00      0.02      0.04        52
          9       1.00      0.11      0.20        53

avg / total       0.93      0.51      0.55       450



**Sigmoid** **SVM**

In [19]:
model=SVC(kernel='sigmoid')
model.fit(x_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='sigmoid',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [0]:
y_pred=model.predict(x_test)

In [21]:
print(confusion_matrix(y_test,y_pred))

[[ 0  0  0  0 43  0  0  0  0  0]
 [ 0  0  0  0 40  0  0  0  0  0]
 [ 0  0  0  0 38  0  0  0  0  0]
 [ 0  0  0  0 52  0  0  0  0  0]
 [ 0  0  0  0 38  0  0  0  0  0]
 [ 0  0  0  0 50  0  0  0  0  0]
 [ 0  0  0  0 45  0  0  0  0  0]
 [ 0  0  0  0 39  0  0  0  0  0]
 [ 0  0  0  0 52  0  0  0  0  0]
 [ 0  0  0  0 53  0  0  0  0  0]]


In [22]:
print(classification_report(y_test,y_pred))

             precision    recall  f1-score   support

          0       0.00      0.00      0.00        43
          1       0.00      0.00      0.00        40
          2       0.00      0.00      0.00        38
          3       0.00      0.00      0.00        52
          4       0.08      1.00      0.16        38
          5       0.00      0.00      0.00        50
          6       0.00      0.00      0.00        45
          7       0.00      0.00      0.00        39
          8       0.00      0.00      0.00        52
          9       0.00      0.00      0.00        53

avg / total       0.01      0.08      0.01       450



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
