In [10]:
#Question 1

import numpy as np
a=np.random.rand(10,1)
print(a)

print("mean = " + str(np.average(a)))

[[ 0.10190505]
 [ 0.34057283]
 [ 0.81196377]
 [ 0.44385724]
 [ 0.5994095 ]
 [ 0.09618022]
 [ 0.70674528]
 [ 0.64897331]
 [ 0.78750767]
 [ 0.39664212]]
mean = 0.49337569839


In [39]:
# Question 2

X=np.random.rand(20,1)
print(arr)

Xbar=float(np.average(X))      #variance
var=(X-Xbar)**2
var=np.sum(var)/20
print("variance = " + str(var))

sd=np.sqrt(var)                #standard deviation
print("Standard Deviation = " + str(sd))

[[ 0.82474906]
 [ 0.37329273]
 [ 0.69833411]
 [ 0.48820897]
 [ 0.67821273]
 [ 0.85896877]
 [ 0.00272412]
 [ 0.91448341]
 [ 0.70822657]
 [ 0.32621517]
 [ 0.70133437]
 [ 0.25924113]
 [ 0.00907448]
 [ 0.82280367]
 [ 0.99036514]
 [ 0.31491186]
 [ 0.95412177]
 [ 0.79189085]
 [ 0.10192908]
 [ 0.35882354]]
variance = 0.0920011793787
Standard Deviation = 0.303316961904


In [43]:
#Question 3

A=np.random.rand(10,20)
B=np.random.rand(20,25)

A=np.dot(A,B)
print(A.shape)

print("Sum of elements is " + str(np.sum(A)))

(10, 25)
Sum of elements is 1288.4622487


In [47]:
#Question 4

arr=np.random.rand(10,1)
print(arr)

b=-1
arr=1/(1+np.exp(arr*b))
print(arr)

[[ 0.45449024]
 [ 0.15414545]
 [ 0.16124991]
 [ 0.34615184]
 [ 0.50496662]
 [ 0.76569366]
 [ 0.1208429 ]
 [ 0.17276938]
 [ 0.71300892]
 [ 0.95211648]]
[[ 0.6117063 ]
 [ 0.53846024]
 [ 0.54022535]
 [ 0.5856841 ]
 [ 0.62362579]
 [ 0.68258861]
 [ 0.53017401]
 [ 0.54308523]
 [ 0.67106568]
 [ 0.72154062]]
